server:
  port: 6001

spring:
  application:
    name: net_trip_getway
  redis:
    host: localhost
    port: 6379
    database: 1
  #    lettuce:
  #      pool:
  #        max-active: 500
  #        max-wait: -1
  #        max-idle: 50
  #        min-idle: 100
  #        time-between-eviction-runs: 180000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
    #        server-addr: 39.108.123.162:8848 #配置Nacos地址
    gateway:
      discovery:
        locator:
          enabled: true       #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: wechat_service #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #          uri: http://localhost:5001          #匹配后提供服务的路由地址
          uri: lb://wechatService                  #配置nacos里面的服务名
          predicates:
            - Path=/user/**         # 断言，路径相匹配的进行路由
          # 过滤器配置
          filters:
            - StripPrefix=0 # 从predicates值的第一个/开始拼接转换
            # 请求限流策略
            - name: RequestRateLimiter
              args: # 采用Redis实现令牌桶限流
                # 令牌生成算法
                keyResolver: '#{@customKeyResolver}'
                # 每秒生成多少令牌
                redis-rate-limiter.replenishRate: 1
                # 令牌桶的上限容量
                redis-rate-limiter.burstCapacity: 5